[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pomodoro-backend"
version = "0.1.0"
description = "Pomodoro backend menggunakan FastAPI dan clean architecture"
authors = ["izulsyaukiimani@gmail.com"]

[tool.poetry.dependencies]
python = ">=3.10"
fastapi = "*"
uvicorn = "*"
SQLAlchemy = "*"
asyncpg = "*"
alembic = "*"
passlib = { version = "*", extras = ["bcrypt"] }
python-jose = "*"
pydantic = "*"

[tool.poetry.dev-dependencies]